import {
  Search,
  Hand,
  DollarSign,
  TrendingUp,
  TrendingDown,
  BarChart3,
  Lightbulb,
  Download,
  RefreshCw,
  Calendar,
  Target,
  Bell,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Home,
  ShoppingCart,
  Coffee,
  Car,
  Plane,
  GraduationCap,
  Briefcase,
  Heart,
  Smartphone,
  Laptop,
  Music,
  Camera,
  Book,
  Dumbbell,
  Pizza,
  Gift,
  CreditCard,
  Wallet,
  Building2,
  PiggyBank,
  Receipt,
  FileText,
  Upload,
  Trash2,
  Edit,
  Plus,
  Minus,
  Eye,
  EyeOff,
  Settings,
  User,
  LogOut,
  Menu,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Filter,
  SortAsc,
  SortDesc,
  Clock,
  MapPin,
  Mail,
  Phone,
  Info,
  HelpCircle,
  Award,
  Star,
  Moon,
  Sun,
  Zap,
  Percent,
  ArrowUpRight,
  ArrowDownRight,
  ArrowRight,
  Copy,
  Check,
  AlertCircle,
  Repeat,
  Share2,
  ExternalLink,
  Layers,
  Package,
  ShoppingBag,
  Utensils,
  Scissors,
  Shirt,
  Tv,
  Gamepad2,
  Headphones,
  Film,
  Palette,
  Umbrella,
  Activity,
  Banknote,
  Landmark,
  CircleDollarSign
} from 'lucide-react';

// Mapping des emojis vers les icônes Lucide
export const iconMap = {
  // Recherche et navigation
  ' ': Search,
  '👋': Hand,
  '🏠': Home,
  '📍': MapPin,
  '👁️': Eye,
  '👁‍🗨': EyeOff,
  
  // Finance
  '💰': DollarSign,
  '💵': Banknote,
  '💳': CreditCard,
  '💸': CircleDollarSign,
  '🏦': Building2,
  '🏧': Landmark,
  '💎': Award,
  '🪙': PiggyBank,
  
  // Graphiques et statistiques
  ' ': TrendingUp,
  ' ': TrendingDown,
  ' ': BarChart3,
  ' ': Calendar,
  ' ': Calendar,
  ' ️': Calendar,
  '⏰': Clock,
  '⏳': Clock,
  '🎯': Target,
  '📋': FileText,
  '📄': FileText,
  '📃': Receipt,
  
  // Actions
  '💡': Lightbulb,
  '📥': Download,
  ' ': RefreshCw,
  '🔔': Bell,
  '⚙️': Settings,
  '✏️': Edit,
  '🗑️': Trash2,
  '➕': Plus,
  '✓': Check,
  '✅': CheckCircle,
  '✕': X,
  '✖': XCircle,
  '⚠️': AlertTriangle,
  'ℹ️': Info,
  '❓': HelpCircle,
  '⭐': Star,
  ' ': Award,
  '🔗': ExternalLink,
  '📎': Upload,
  '📤': Upload,
  '📂': Package,
  
  // Catégories de dépenses
  '🛒': ShoppingCart,
  '🛍️': ShoppingBag,
  '☕': Coffee,
  '🍕': Pizza,
  '🍽️': Utensils,
  '🚗': Car,
  '✈️': Plane,
  '🎓': GraduationCap,
  '💼': Briefcase,
  '❤️': Heart,
  '📱': Smartphone,
  '💻': Laptop,
  '🎸': Music,
  '🎵': Headphones,
  '📷': Camera,
  '📚': Book,
  '🏋️': Dumbbell,
  '🎁': Gift,
  '👕': Shirt,
  '✂️': Scissors,
  '📺': Tv,
  '🎮': Gamepad2,
  '🎬': Film,
  '🎨': Palette,
  '☂️': Umbrella,
  
  // Direction
  ' ': ArrowRight,
  '◀': ChevronLeft,
  '▲': ChevronUp,
  '▼': ChevronDown,
  '⬇️': ChevronDown,
  '➡️': ArrowRight,
  '↗': ArrowUpRight,
  '↘': ArrowDownRight,
  
  // Mode
  '🌙': Moon,
  '☀️': Sun,
  
  // Utilisateur
  '👤': User,
  '🚪': LogOut,
  
  // Autres
  '🔥': Zap,
  '💯': Percent,
  '📦': Package,
  '🔀': Repeat,
  '🔁': Repeat,
  '📤': Share2,
  '🎯': Target,
  '💪': Activity,
  '📌': MapPin,
  '✉️': Mail,
  '📞': Phone,
  '🍔': Utensils,
  '🏨': Building2,
  '🏪': Building2,
  '🏫': GraduationCap,
  '🏥': Heart,
  '⚽': Activity,
  '🎾': Activity,
  '🎭': Palette,
};

// Composant Icon universel
export const Icon = ({ emoji, className = '', size = 20, color = 'currentColor', ...props }) => {
  const IconComponent = iconMap[emoji];
  
  if (!IconComponent) {
    // Si l'emoji n'est pas mappé, retourner l'emoji
    return <span className={className} {...props}>{emoji}</span>;
  }
  
  return <IconComponent size={size} color={color} className={className} {...props} />;
};

export default Icon;